### ISSUE TITLE
comparison with the most popular option

### ISSUE THREAD

**Issue by balupton** [koj-co/dependabot-pr-action#8]
currently for github actions that automerge dependabot PRs, there is this repo which only star is mine, and this one https://github.com/ahmadnassri/action-dependabot-auto-merge which has many stars

what is a comparison between them

how does the cron job thing work, why is it not the pull_request event?

does the automatic github provifded `GITHUB_TOKEN` work with this? as it does not work with the other one

**Comment by pabio-escobar** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by balupton** [comment]
ping @AnandChowdhary

**Comment by AnandChowdhary** [comment]
Hey @balupton,

The main difference about these projects is that `action-dependabot-auto-merge` asks Dependabot to merge the PR based on options, whereas this action merges PRs itself. This gives us more flexibility to add rules, and instead of running on every pull request event, we run it once (or a few times) per day, when we merge all Dependabot PRs at once. This also saves CI minutes.

For the token, you need to supply a personal access token.

**Comment by pabio-escobar** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.
